server:
  port: 10003
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/paascloud_uac?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
  security:
    user:
      name: admin
      password: admin
  cloud:
    sentinel:
      transport:
        dashboard: 111.231.57.87:8091
        port: 8719
      datasource:
        flow:
          nacos:
            server-addr: nepous.nacos.com:8848
            dataId: nepous-provider-uac-flow-rules
            groupId: SENTINEL_GROUP
            rule-type: flow
        degrade:
          nacos:
            server-addr: nepous.nacos.com:8848
            dataId: ${spring.application.name}-degrade-rules
            groupId: SENTINEL_GROUP
            rule-type: degrade
          system:
            nacos:
              server-addr: nepous.nacos.com:8848
              dataId: ${spring.application.name}-system-rules
              groupId: SENTINEL_GROUP
              rule-type: system
          authority:
            nacos:
              server-addr: nepous.nacos.com:8848
              dataId: ${spring.application.name}-authority-rules
              groupId: SENTINEL_GROUP
              rule-type: authority
          param-flow:
            nacos:
              server-addr: nepous.nacos.com:8848
              dataId: ${spring.application.name}-param-flow-rules
              groupId: SENTINEL_GROUP
              rule-type: param-flow

logging:
  level:
    com.nepous.provider.mapper: trace


mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  config-location: classpath:/mybatis-config.xml
nepous:
  swagger:
    title: 'UAC--用户权限控制中心'