server:
  port: 10003
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/paascloud_uac?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root

logging:
  level:
    com.nepous.provider.mapper: trace


mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  config-location: classpath:/mybatis-config.xml
nepous:
  swagger:
    title: 'UAC--用户权限控制中心'