spring:
  application:
    name: nepous-gateway
  cloud:
    nacos:
      discovery:
        server-addr: nepous.nacos.com:8848
        namespace: 0c0760cc-b7a9-44ad-95b2-a949c025ab26
        group: dev



