spring:
  cloud:
    nacos:
      discovery:
        server-addr: nepous.nacos.com:8848
  application:
    name: nepous-provider-uac
nepous:
  security:
    oauth2:
      clients[0]:
        clientId: nepous
        clientSecret: nepous
        scope: "*"
      tokenStore: jwt
      jwtSigningKey: nepous
  zk:
    zkAddressList: 111.231.57.87:2181